import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CRM App",
  description: "Generated by create next app!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <div
          className="bg-gray-200"
          style={{
            height: "90vh",
            width: "90vw",
            display: "flex",
            flexDirection: "column",
          }}
        >
          {/* Header */}
          <div className="bg-gray-500">Header</div>

          {children}
        </div>
      </body>
    </html>
  );
}
